# Generated by Django 6.0.2 on 2026-02-13 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المسابقة/الدرس')),
                ('video_url', models.URLField(verbose_name='رابط فيديو يوتيوب')),
                ('video_duration', models.IntegerField(verbose_name='مدة الفيديو (بالدقائق)')),
                ('reading_text', models.TextField(verbose_name='نص مرحلة القراءة')),
                ('reading_timer', models.IntegerField(verbose_name='وقت القراءة (بالدقائق)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('text', 'سؤال مقالي')], default='mcq', max_length=10, verbose_name='نوع السؤال')),
                ('question_text', models.CharField(max_length=500, verbose_name='نص السؤال')),
                ('option_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاختيار 1')),
                ('option_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاختيار 2')),
                ('option_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاختيار 3')),
                ('option_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاختيار 4')),
                ('correct_option', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='الإجابة الصح')),
                ('points', models.IntegerField(default=1, verbose_name='النقاط')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.lesson', verbose_name='الدرس التابع له')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.IntegerField(default=0, verbose_name='إجمالي السكور')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('date_completed', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.lesson', verbose_name='المسابقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentprogress', to=settings.AUTH_USER_MODEL, verbose_name='الطالبة')),
            ],
        ),
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='إجابة الطالبة')),
                ('points_earned', models.IntegerField(default=0, verbose_name='الدرجة اللي خدتها')),
                ('is_graded', models.BooleanField(default=False, verbose_name='اتصححت؟')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_answers', to='course.studentprogress')),
            ],
        ),
    ]
